spring:
  application:
    name: streaming-app-backend


  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver



  jpa:
      hibernate:
        ddl-auto: update

      show-sql: true

      properties:
        hibernate:
          format_sql: true

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

aws:
  s3:
    bucket-name: ${AWS_BUCKET_NAME}
    region: ${AWS_REGION}
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}




files:
  video: videos/
  hls: videos_hls/


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    name: Java_Streaming_Queue
  exchange:
    name: Java_Streaming_Exchange
  key:
    value: Java_Streaming_routing_key_streaming


jwt:
  secret: mySuperSecretKeyForJwtAuthentication123456789
  expiration: 86400000
