spring:
  application:
    name: streaming-app-backend


  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver



  jpa:
      hibernate:
        ddl-auto: update

      show-sql: true

      properties:
        hibernate:
          format_sql: true

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

aws:
  s3:
    bucket-name: ${AWS_BUCKET_NAME}
    region: ${AWS_REGION}
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}




files:
  video: videos/
  hls: videos_hls/